### ISSUE TITLE
[Security] Workflow update-license-year.yml is using vulnerable action FantasticFiasco/action-update-license-year

### ISSUE THREAD

**Issue by Freakston** [aifrak/dotfiles#96]
The workflow update-license-year.yml is referencing action FantasticFiasco/action-update-license-year using references v2.1.0. However this reference is missing the commit [0dd479f24c62cdbbbce52c7f2ee4277c778cae06](https://github.com/FantasticFiasco/action-update-license-year/commits/0dd479f24c62cdbbbce52c7f2ee4277c778cae06) which may contain fix to the some vulnerability. 
The vulnerability fix that is missing by actions version could be related to: 
(1) CVE fix 
(2) upgrade of vulnerable dependency 
(3) fix to secret leak and others. 
Please consider to update the reference to the action.

**Comment by aifrak** [comment]
@Freakston Thank you for reporting the issue.

I did not expect someone visiting on one of my repos :)

It should be fixed now. I point the action to the commit SHA.
